### ISSUE TITLE
axes not working properly?

### ISSUE THREAD

**Issue by shadowleeman3** [mechobree/terrafabrica#2]
Hi, I've played a bit and none of the axes work properly on trees. The time needed to cut down a tree is still the same as cutting it by hand. The hammer, on the other hand, cuts them as fast as an ax should, but only sticks fall out of the log block.

**Comment by mechobree** [comment]
I remember having this issue while developing, it appeared to be an issue with additional placement tags being messed up, this should have been fixed in one of the updates as I have removed that mod from the pack. 

Do you still have that mod enabled?

**Comment by shadowleeman3** [comment]
I downloaded the package a few hours before reporting this problem. I don't see it in the mods folder but the problem still occurs.

**Comment by mechobree** [comment]
Oh what in the world? What's causing that haha.
Give me a bit, this might take awhile to figure out how to fix, I recommend rolling back a version rather than waiting :p

**Comment by mechobree** [comment]
Uploaded a new version, 1.14.1a, and it worked when I downloaded a new instance on another pc.
Can you check it out to see if it fixed it for you too?

**Comment by shadowleeman3** [comment]
I reinstalled to 1.15 and it works just fine, thank you ^^

**Comment by mechobree** [comment]
Awesome! I literally changed nothing, must have been an error in the other export. Glad it's fixed though!
